 <?php

function lowerify_menu() {
  $items = array();
  $items['lowerify'] = array(
    'title' => 'Lowercase This',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('poem_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['lower_success_page'] = array(
    'title' => 'this poem is a masterpiece now',
    'page callback' => 'lower_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function poem_form() {
  $form['poem_title'] = array(
    '#title' => t('poem title'),
    '#type' => 'textfield',
    '#description' => t('enter the title of your poem'),
    '#required' => TRUE,
  );

  $form['poem_body'] = array(
    '#title' => t('poem body'),
    '#type' => 'textarea',
    '#description' => t('enter the body of your poem'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'lowerify this',
  );

  return $form;
}

function poem_form_submit($form, &$form_state) {
  $lowered_string = "";

  $body_to_lower = $form_state['values']['poem_body'];
  $title_to_lower = $form_state['values']['poem_title'];

  $body_to_lower = strtolower($body_to_lower);
  $title_to_lower = strtolower($title_to_lower);

  $lowered_string = $title_to_lower.'<br>'.$body_to_lower;

  $_SESSION['lowered'] = $lowered_string;
  $form_state['redirect'] = 'lower_success_page';
}

function lower_success() {
  $lowered_poem = $_SESSION['lowered'];
  return $lowered_poem;
}
