 <?php

function lowerify_menu() {
  $items = array();
  $items['lowerify'] = array(
    'title' => 'Lowercase This',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('poem_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['lower_success_page'] = array(
    'title' => 'this poem is a masterpiece now',
    'page callback' => 'lower_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['nah_page'] = array(
    'title' => 'youre good?',
    'page callback' => 'nah_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function poem_form() {
  $form['poem_title'] = array(
    '#title' => t('poem title'),
    '#type' => 'textfield',
    '#description' => t('enter the title of your poem'),
    '#required' => TRUE,
  );

  $form['poem_body'] = array(
    '#title' => t('poem body'),
    '#type' => 'textarea',
    '#description' => t('enter the body of your poem'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'submit',
    '#submit' => array('lowerify_confirm_poem_submit'),
  );

  $form['nah'] = array(
    '#type' => 'submit',
    '#value' => 'nahh',
    '#submit' => array('lowerify_false_poem_submit'),
  );

  return $form;
}

function lowercase_everything($input) {
  $input = strtolower($input);
  return $input;
}

function lowerify_confirm_poem_submit($form, &$form_state) {
  $lowered_string = "";
  $body_to_lower = $form_state['values']['poem_body'];
  $title_to_lower = $form_state['values']['poem_title'];

  $body_to_lower = lowercase_everything($body_to_lower);
  $title_to_lower = lowercase_everything($title_to_lower);

  $lowered_string = $title_to_lower.'<br>'.$body_to_lower;

  $_SESSION['lowered'] = $lowered_string;
  $form_state['redirect'] = 'lower_success_page';
}

function lowerify_false_poem_submit($form, &$form_state) {
  $form_state['redirect'] = 'nah_page';
}

function lower_success() {
  $lowered_poem = $_SESSION['lowered'];
  return "$lowered_poem ee cummings would be proud! ";
}

function nah_success() {
  return "way to be dramatic...with those capitalized words...";
}
